language: cpp
dist: bionic
os:
 - linux
addons:
  apt:
    packages:
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-system-dev

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libboost-dev libboost-filesystem-dev libboost-system-dev

script:
 - mkdir build && cd build
 - cmake ../core
 - make -j10
 - cd ..
 - mkdir build-unit && cd build-unit
 - cmake ../test/unit
 - make
 - ./ZXingUnitTest
 - cd ..
 - mkdir build-test && cd build-test
 - cmake -DCMAKE_BUILD_TYPE=Release ../test/runners/generic/
 - make
 - ./ReaderTest ../test/
